


<CameraClick>:
	
    KivyCamera:
        id: qrcam
		
	
    Button:
        text: 'Capture'
        size_hint: (.3, .1)
        pos_hint: {'x': .4, 'y': .05}
        on_press: root.capture()




<SettingsScreen>:
    FloatLayout:
		id: settings
		ImgDisplay:
		    id: grid
			
        Button:
            text: 'Crop'
            size_hint: (.2, .1)
            pos_hint: {'x': .2, 'y': .05}
			on_press: root.crop_grid_img()
			
        Button:
            text: 'Try again'
            size_hint: (.2, .1)
            pos_hint: {'x': .6, 'y': .05}
			on_press: root.go_back()


			
<CropScreen>:
    FloatLayout:
		ImgDisplay:
		    id: crop
			size: 500, 500
			
        Button:
            text: 'Try again'
            size_hint: (.3, .1)
            pos_hint: {'x': .6, 'y': .05}
			on_press: root.go_back()
			
        Button:
            text: 'Solve'
            size_hint: (.3, .1)
            pos_hint: {'x': .2, 'y': .05}
			on_press: root.go_to_solve()
	
			
<SolvedScreen>:
	ImgDisplay:
	    id: solved
		size: 500, 500
		
	Button:
		text: 'Try again'
		size_hint: (.4, .1)
		pos_hint: {'x': .3, 'y': .05}
		on_press: root.select_new()
			
			
<NoSolScreen>:
    FloatLayout:
		Label:
			id: label_widget
		    text: 'No Solution Found'
			
        Button:
            text: 'Try again'
            size_hint: (.3, .1)
            pos_hint: {'x': .4, 'y': .05}
			on_press: root.select_new()